<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd11e94af621bca9c4fb0a779a054de8a
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Mike42\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Mike42\\' => 
        array (
            0 => __DIR__ . '/..' . '/mike42/escpos-php/src/Mike42',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd11e94af621bca9c4fb0a779a054de8a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd11e94af621bca9c4fb0a779a054de8a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
